# Generated by Django 6.0.7 on 2026-07-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('feed_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('exchange', 'Exchange'), ('news', 'News'), ('data', 'Market Data'), ('social', 'Social / Sentiment'), ('research', 'Research')], default='exchange', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
    ]
