# Generated by Django 5.0.6 on 2026-08-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_notification_alertrule'),
        ('alerts', '0002_watchitem'),
    ]

    operations = [
    ]
