# Generated by Django 5.0.6 on 2026-06-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Friendly name shown in the UI', max_length=120)),
                ('provider_type', models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('ollama', 'Ollama (local)'), ('custom', 'Custom (OpenAI-compatible)')], default='deepseek', max_length=20)),
                ('base_url', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('temperature', models.FloatField(default=0.4)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'label'],
            },
        ),
    ]
