# Generated by Django 5.0.6 on 2026-06-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('github', 'GitHub Models'), ('ollama', 'Ollama (local)'), ('custom', 'Custom (OpenAI-compatible)')], default='deepseek', max_length=20),
        ),
    ]
