# Generated by Django 5.0.6 on 2026-06-22 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='demo', max_length=40, unique=True)),
                ('broker', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('balance', models.FloatField(default=0)),
                ('equity', models.FloatField(default=0)),
                ('margin', models.FloatField(default=0)),
                ('free_margin', models.FloatField(default=0)),
                ('leverage', models.IntegerField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('gold_symbol', models.CharField(blank=True, max_length=40)),
                ('silver_symbol', models.CharField(blank=True, max_length=40)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MT5Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('bid', models.FloatField(default=0)),
                ('ask', models.FloatField(default=0)),
                ('spread', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MT5Candles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=8)),
                ('candles', models.JSONField(default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('symbol', 'timeframe')},
            },
        ),
        migrations.CreateModel(
            name='MT5Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=4)),
                ('volume', models.FloatField(default=0.01)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('filled', 'filled'), ('rejected', 'rejected'), ('error', 'error')], default='pending', max_length=10)),
                ('ticket', models.BigIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
