# Generated by Django 5.0.6 on 2026-07-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('bid', models.FloatField(default=0)),
                ('ask', models.FloatField(default=0)),
                ('tick_dir', models.SmallIntegerField(default=0)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'ts'], name='mt5_mt5tick_symbol_e61959_idx')],
            },
        ),
    ]
