# Generated by Django 5.0.6 on 2026-08-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_expiringtoken_user'),
        ('accounts', '0002_systemsetting'),
    ]

    operations = [
    ]
