# Generated by Django 5.0.6 on 2026-06-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='e.g. BTCUSDT', max_length=32, unique=True)),
                ('name', models.CharField(help_text='e.g. Bitcoin', max_length=120)),
                ('category', models.CharField(choices=[('crypto', 'Crypto'), ('metal', 'Metal'), ('forex', 'Forex'), ('stock', 'Stock'), ('index', 'Index')], default='crypto', max_length=16)),
                ('tradingview_symbol', models.CharField(blank=True, max_length=64)),
                ('binance_symbol', models.CharField(blank=True, max_length=32)),
                ('is_watched', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'symbol'],
            },
        ),
    ]
