# Generated by Django 6.0.7 on 2026-07-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('key', models.CharField(choices=[('rsi', 'RSI'), ('macd', 'MACD'), ('ema', 'EMA'), ('sma', 'SMA'), ('bollinger', 'Bollinger Bands'), ('fibonacci', 'Fibonacci Retracement'), ('stoch', 'Stochastic'), ('ichimoku', 'Ichimoku'), ('volume', 'Volume'), ('support_resistance', 'Support / Resistance'), ('custom', 'Custom')], default='rsi', max_length=24)),
                ('settings', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="Without @, e.g. 'whalepool'", max_length=100)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'username'],
            },
        ),
    ]
