# Generated by Django 6.0.7 on 2026-07-08 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('tradingview_symbol', models.CharField(blank=True, max_length=60)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=8)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('tp1_price', models.FloatField(blank=True, null=True)),
                ('tp1_pct', models.FloatField(default=40)),
                ('tp1_done', models.BooleanField(default=False)),
                ('tp2_price', models.FloatField(blank=True, null=True)),
                ('tp2_pct', models.FloatField(default=35)),
                ('tp2_done', models.BooleanField(default=False)),
                ('tp3_price', models.FloatField(blank=True, null=True)),
                ('tp3_pct', models.FloatField(default=25)),
                ('tp3_done', models.BooleanField(default=False)),
                ('remaining_pct', models.FloatField(default=100)),
                ('realized_pnl', models.FloatField(default=0)),
                ('size', models.FloatField(default=0)),
                ('leverage', models.FloatField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('pnl_percent', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('setup_class', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
