# Generated by Django 5.0.6 on 2026-07-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='setup_class',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
