# Generated by Django 5.0.6 on 2026-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_setup_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
