# Generated by Django 5.0.6 on 2026-07-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='quantity',
        ),
    ]
