# Generated by Django 5.0.6 on 2026-07-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_remove_trade_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='realized_pnl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='remaining_pct',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp1_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp1_pct',
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp1_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp2_pct',
            field=models.FloatField(default=35),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp2_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp3_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp3_pct',
            field=models.FloatField(default=25),
        ),
        migrations.AddField(
            model_name='trade',
            name='tp3_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
