# Generated by Django 5.0.6 on 2026-07-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_fix_bitunix_mirror_size'),
        ('trades', '0005_trade_realized_pnl_trade_remaining_pct_and_more'),
    ]

    operations = [
    ]
