# Generated by Django 5.0.6 on 2026-08-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_strategy_attribution'),
        ('trades', '0006_merge_20260730_2027'),
    ]

    operations = [
    ]
