# Generated by Django 5.0.6 on 2026-06-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTraderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('accounts_json', models.JSONField(default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
